### ISSUE TITLE
Question about when to perform l2 normalization

### ISSUE THREAD

**Issue by Pixie8888** [dvlab-research/GFS-Seg#7]
Hi,

Thanks for releasing the code. I notice that at some prototype fusion step, the corresponding feature are normalised, like this:https://github.com/dvlab-research/GFS-Seg/blob/c5bb735d4dd24e9fad8b4330c8dd8a7ce8ae0f04/model/capl.py#L139 and this: https://github.com/dvlab-research/GFS-Seg/blob/c5bb735d4dd24e9fad8b4330c8dd8a7ce8ae0f04/model/capl.py#L208.
While the implementation of eqn7 does not perform l2 normalisation: https://github.com/dvlab-research/GFS-Seg/blob/c5bb735d4dd24e9fad8b4330c8dd8a7ce8ae0f04/model/capl.py#L243.

I am confused when to perform l2 normalisation. Could you please give some suggestion? Thanks!

**Comment by tianzhuotao** [comment]
Thank you for being interested in our work!

To be honest, there were no rules / strategies for adding the L2 normalizations. In our experiments, as long as the L2 norm has been performed before yielding the predictions, the results won't change much. You may try deleting unnecessary lines, such as the one in line 208 since the concatenation of the prototypes will be normalized in line 215 later.

Sorry for the inconvenience caused by the messy part of our code.

**Comment by Pixie8888** [comment]
Okay.
